version: '3'
services:

  loonflow-web:
    hostname: loonflow-web
    build:
      context: ./loonflow-web
      dockerfile: Dockerfile
    ports:
      - "6060:6060"
    command:
      - /bin/sh
      - -c
      - |
        cd /opt/loonflow
        python3 manage.py makemigrations
        python3 manage.py runserver 0.0.0.0:6060
    network_mode: "host"
    depends_on:
      - redis

  redis:
    hostname: redis
    image: redis:alpine
    expose:
      - "6379"
    network_mode: "host"

  loonflow-task:
    hostname: loonflow-task
    build:
      context: ./loonflow-task
      dockerfile: Dockerfile
    network_mode: "host"
    command:
      - /bin/sh
      - -c
      - |
        cd /opt/loonflow
        celery -A tasks worker -l info -c 8 -Q loonflow

  shutongflow:
    hostname: shutongflow
    build:
      context: ./shutongflow
      dockerfile: Dockerfile
    ports:
      - 6061:6061
      - 6062:6062
    network_mode: "host"
    command:
      - /bin/sh
      - -c
      - |
        cd /opt/shutongFlow/apps
        python3 manage.py makemigrations
        python3 manage.py migrate
        nohup python3 manage.py runserver 0.0.0.0:6062 &
        cd /opt/shutongFlow/fronted
        cnpm run dev
